### ISSUE TITLE
ImportError: No module named itools.datatypes on 0.62

### ISSUE THREAD

**Issue by nkhine** [hforge/itools#3]
installing itools 0.62 using pip to install itools, as

$ pip -vr requirements.txt

contents of which is:

http://effbot.org/media/downloads/Imaging-1.1.7.tar.gz
docutils>=0.8
-e git+https://github.com/numpy/numpy.git#egg=numpy
-e git+https://github.com/matplotlib/matplotlib.git#egg=matplotlib
nose>=1.1.2
pygit2>=0.17.0
python-dateutil>=1.5
python-magic>=0.4.1
pytz>=2012c
reportlab>=2.5
wsgiref>=0.1.2
xlrd>=0.7.1
-e git://github.com/hforge/itools.git@0.62#egg=itools
-e git://github.com/hforge/ikaaro.git@0.62#egg=ikaaro
-e git://github.com/hforge/wiki.git#egg=wiki

but get this error:

```
Running setup.py egg_info for package itools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/__init__.py", line 2, in <module>
        # Copyright (C) 2004, 2006, 2008-2009 J. David Ibáñez <jdavid.ibp@gmail.com>
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/extension.py", line 2, in <module>
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 6, in <module>
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/sdist.py", line 5, in <module>
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 698, in <module>
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 701, in Environment
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 99, in get_supported_platform
      File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 209, in _macosx_vers
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/platform.py", line 803, in mac_ver
        info = _mac_ver_xml()
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/platform.py", line 780, in _mac_ver_xml
        pl = plistlib.readPlist(fn)
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/plistlib.py", line 78, in readPlist
        rootObject = p.parse(pathOrFile)
      File "/usr/local/Cellar/python/2.7.2/lib/python2.7/plistlib.py", line 401, in parse
        from xml.parsers.expat import ParserCreate
      File "xml/__init__.py", line 20, in <module>
        import dublin_core
      File "xml/dublin_core.py", line 20, in <module>
        from itools.datatypes import Unicode, String, ISODateTime
    ImportError: No module named itools.datatypes
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/__init__.py", line 2, in <module>

    # Copyright (C) 2004, 2006, 2008-2009 J. David Ibáñez <jdavid.ibp@gmail.com>

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/extension.py", line 2, in <module>

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 6, in <module>

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/command/sdist.py", line 5, in <module>

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 698, in <module>

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 701, in Environment

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 99, in get_supported_platform

  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 209, in _macosx_vers

  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/platform.py", line 803, in mac_ver

    info = _mac_ver_xml()

  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/platform.py", line 780, in _mac_ver_xml

    pl = plistlib.readPlist(fn)

  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/plistlib.py", line 78, in readPlist

    rootObject = p.parse(pathOrFile)

  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/plistlib.py", line 401, in parse

    from xml.parsers.expat import ParserCreate

  File "xml/__init__.py", line 20, in <module>

    import dublin_core

  File "xml/dublin_core.py", line 20, in <module>

    from itools.datatypes import Unicode, String, ISODateTime

ImportError: No module named itools.datatypes

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/req.py", line 941, in prepare_files
    req_to_install.run_egg_info()
  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/req.py", line 222, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/khinester/.virtualenvs/phoenix/lib/python2.7/site-packages/pip-1.0.2-py2.7.egg/pip/__init__.py", line 255, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
```

what am i missing?

**Comment by staverne** [comment]
This bug has been fixed in last versions.
I close.
