### ISSUE TITLE
Unable to install via pip (first install)

### ISSUE THREAD

**Issue by fchenebault** [hforge/itools#41]
When first installing itools via pip :
`pip install https://github.com/hforge/itools.git`

I got this issue :

```
    ** (process:13000): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

    ** (process:13000): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

    ** (process:13000): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'

    [WARNING] wv2 not found, DOC indexation won't work

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/var/folders/qm/n167d_8d1w31h7fc5zt9q94w0000gp/T/pip-drfz9_-build/setup.py", line 87, in <module>

        setup(ext_modules=ext_modules)

      File "itools/pkg/utils.py", line 130, in setup

        filenames = [ x.strip() for x in open('MANIFEST').readlines() ]

    IOError: [Errno 2] No such file or directory: 'MANIFEST'

```

**Comment by fchenebault** [comment]
My mistake this have been fixed in one of the last commits !
