### ISSUE TITLE
easy_install failure for itools 0.75

### ISSUE THREAD

**Issue by jbq** [hforge/itools#9]
I'd like an easy way to install itools with pip.  Since itools has used the git2 module, easy_install chokes on this dependency.  Is it maybe possible to package itools without the git2 module?

```
$ sudo easy_install itools
Searching for itools
Reading http://pypi.python.org/simple/itools/
Reading http://www.hforge.org/itools
Reading http://sf.net/projects/lleu
Reading http://www.ikaaro.org
Reading http://www.ikaaro.org/itools
Best match: itools 0.75.0
Downloading http://pypi.python.org/packages/source/i/itools/itools-0.75.0.tar.gz#md5=2ffefb6f30eed86b2775c6e967015ebe
Processing itools-0.75.0.tar.gz
Running itools-0.75.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xyHsHu/itools-0.75.0/egg-dist-tmp-VzBOyi
Traceback (most recent call last):
  File "/usr/bin/easy_install", line 9, in <module>
    load_entry_point('distribute==0.6.24dev-r0', 'console_scripts', 'easy_install')()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1931, in main
    with_ei_usage(lambda:
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1912, in with_ei_usage
    return f()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1935, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 368, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 608, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 638, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 828, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1105, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1094, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 30, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 72, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 32, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 29, in <module>
  File "/tmp/easy_install-xyHsHu/itools-0.75.0/pkg/__init__.py", line 25, in <module>

  File "/tmp/easy_install-xyHsHu/itools-0.75.0/pkg/utils.py", line 32, in <module>
  File "/tmp/easy_install-xyHsHu/itools-0.75.0/git/__init__.py", line 18, in <module>

  File "/tmp/easy_install-xyHsHu/itools-0.75.0/git/worktree.py", line 28, in <module>
ImportError: No module named pygit2
```

**Comment by staverne** [comment]
Now pygit2 is available via PIP.
We've also added pygit2 in requirements.txt
I close.
